// Các bảng mẫu kiểu MathType. `t` = mẫu chèn (MathLive): #0 = vùng chọn/ô trống đầu, #? = ô trống.
// `p` = LaTeX hiển thị trên nút (mặc định: t với ô trống). `h` = chú thích khi rê chuột.

const S = (list) => list.map((t) => (typeof t === 'string' ? { t } : t));

export const PALETTES = [
  {
    id: 'basic', label: 'Cơ bản',
    items: S([
      { t: '\\frac{#0}{#?}', h: 'Phân số (gõ tắt: /)' },
      { t: '\\dfrac{#0}{#?}', h: 'Phân số cỡ lớn' },
      { t: '{#0}/{#?}', h: 'Phân số gạch chéo' },
      { t: '\\sqrt{#0}', h: 'Căn bậc hai (gõ: sqrt)' },
      { t: '\\sqrt[#?]{#0}', h: 'Căn bậc n' },
      { t: '{#0}^{#?}', h: 'Số mũ (gõ: ^)' },
      { t: '{#0}_{#?}', h: 'Chỉ số dưới (gõ: _)' },
      { t: '{#0}_{#?}^{#?}', h: 'Chỉ số dưới và mũ' },
      { t: '{}_{#?}^{#?}{#0}', h: 'Chỉ số bên trái' },
      { t: '\\left(#0\\right)', h: 'Ngoặc tròn co giãn' },
      { t: '\\left[#0\\right]', h: 'Ngoặc vuông' },
      { t: '\\left\\{#0\\right\\}', h: 'Ngoặc nhọn' },
      { t: '\\left|#0\\right|', h: 'Giá trị tuyệt đối' },
      { t: '\\left\\|#0\\right\\|', h: 'Chuẩn' },
      { t: '\\left\\langle #0\\right\\rangle', h: 'Ngoặc góc' },
      { t: '\\left\\lfloor #0\\right\\rfloor', h: 'Phần nguyên dưới' },
      { t: '\\left\\lceil #0\\right\\rceil', h: 'Phần nguyên trên' },
      { t: '\\left(#0\\right]', h: 'Nửa khoảng' },
      { t: '\\left[#0\\right)', h: 'Nửa khoảng' },
      { t: '\\left.#0\\right|_{#?}^{#?}', h: 'Thay cận' },
      { t: '#0\\cdot 10^{#?}', h: 'Dạng khoa học' },
      { t: '\\text{#0}', p: '\\text{Chữ}', h: 'Chữ thường (gõ tiếng Việt)' },
    ]),
  },
  {
    id: 'calc', label: 'Tổng & Tích phân',
    items: S([
      { t: '\\sum_{#?}^{#?}#0', h: 'Tổng có cận' },
      { t: '\\sum_{#?}#0', h: 'Tổng cận dưới' },
      { t: '\\prod_{#?}^{#?}#0', h: 'Tích' },
      { t: '\\coprod_{#?}^{#?}#0', h: 'Đối tích' },
      { t: '\\int #0\\,\\mathrm{d}#?', h: 'Nguyên hàm' },
      { t: '\\int_{#?}^{#?}#0\\,\\mathrm{d}#?', h: 'Tích phân xác định' },
      { t: '\\iint_{#?}#0\\,\\mathrm{d}#?\\,\\mathrm{d}#?', h: 'Tích phân kép' },
      { t: '\\iiint_{#?}#0', h: 'Tích phân bội ba' },
      { t: '\\oint_{#?}#0', h: 'Tích phân đường kín' },
      { t: '\\lim_{#?\\to #?}#0', h: 'Giới hạn' },
      { t: '\\lim_{x\\to +\\infty}#0', h: 'Giới hạn tại +∞' },
      { t: '\\lim_{x\\to #?^{+}}#0', h: 'Giới hạn phải' },
      { t: '\\frac{\\mathrm{d}#0}{\\mathrm{d}#?}', h: 'Đạo hàm' },
      { t: '\\frac{\\mathrm{d}^{2}#0}{\\mathrm{d}#?^{2}}', h: 'Đạo hàm cấp 2' },
      { t: '\\frac{\\partial #0}{\\partial #?}', h: 'Đạo hàm riêng' },
      { t: "{#0}'", p: "f'", h: 'Đạo hàm (phẩy)' },
      { t: "{#0}''", p: "f''", h: 'Đạo hàm cấp 2' },
      { t: '\\bigcup_{#?}^{#?}#0', h: 'Hợp' },
      { t: '\\bigcap_{#?}^{#?}#0', h: 'Giao' },
      { t: '\\max_{#?}#0', h: 'Max' },
      { t: '\\min_{#?}#0', h: 'Min' },
      { t: '\\sup_{#?}#0', h: 'Cận trên' },
    ]),
  },
  {
    id: 'matrix', label: 'Ma trận & Hệ',
    items: S([
      { t: '\\begin{cases}#0\\\\#?\\end{cases}', h: 'Hệ 2 phương trình' },
      { t: '\\begin{cases}#0\\\\#?\\\\#?\\end{cases}', h: 'Hệ 3 phương trình' },
      { t: '\\left[\\begin{array}{l}#0\\\\#?\\end{array}\\right.', h: 'Tuyển (hoặc) 2 dòng' },
      { t: '\\left[\\begin{array}{l}#0\\\\#?\\\\#?\\end{array}\\right.', h: 'Tuyển 3 dòng' },
      { t: '\\begin{cases}#0 & #?\\\\#? & #?\\end{cases}', h: 'Hàm từng khúc' },
      { t: '\\begin{aligned}#0&=#?\\\\&=#?\\end{aligned}', h: 'Biến đổi thẳng hàng dấu =' },
      { t: '\\begin{pmatrix}#0&#?\\\\#?&#?\\end{pmatrix}', h: 'Ma trận 2×2' },
      { t: '\\begin{pmatrix}#0&#?&#?\\\\#?&#?&#?\\\\#?&#?&#?\\end{pmatrix}', h: 'Ma trận 3×3' },
      { t: '\\begin{bmatrix}#0&#?\\\\#?&#?\\end{bmatrix}', h: 'Ma trận ngoặc vuông' },
      { t: '\\begin{vmatrix}#0&#?\\\\#?&#?\\end{vmatrix}', h: 'Định thức 2×2' },
      { t: '\\begin{vmatrix}#0&#?&#?\\\\#?&#?&#?\\\\#?&#?&#?\\end{vmatrix}', h: 'Định thức 3×3' },
      { t: '\\begin{pmatrix}#0\\\\#?\\\\#?\\end{pmatrix}', h: 'Vector cột' },
      { t: '\\begin{pmatrix}#0&#?&#?\\end{pmatrix}', h: 'Vector hàng' },
      { t: '\\begin{matrix}#0&#?\\\\#?&#?\\end{matrix}', h: 'Bảng không ngoặc' },
      { t: '\\binom{#0}{#?}', h: 'Nhị thức' },
      { t: '\\cdots', h: 'Ba chấm giữa' },
      { t: '\\ldots', h: 'Ba chấm dưới' },
      { t: '\\vdots', h: 'Ba chấm dọc' },
      { t: '\\ddots', h: 'Ba chấm chéo' },
    ]),
  },
  {
    id: 'accent', label: 'Dấu trên/dưới',
    items: S([
      { t: '\\overrightarrow{#0}', p: '\\overrightarrow{AB}', h: 'Vector AB' },
      { t: '\\vec{#0}', p: '\\vec{u}', h: 'Vector' },
      { t: '\\overline{#0}', p: '\\overline{AB}', h: 'Gạch trên' },
      { t: '\\underline{#0}', p: '\\underline{x}', h: 'Gạch dưới' },
      { t: '\\widehat{#0}', p: '\\widehat{ABC}', h: 'Góc' },
      { t: '\\hat{#0}', p: '\\hat{x}', h: 'Mũ' },
      { t: '\\tilde{#0}', p: '\\tilde{x}', h: 'Ngã' },
      { t: '\\bar{#0}', p: '\\bar{x}', h: 'Gạch ngang' },
      { t: '\\dot{#0}', p: '\\dot{x}', h: 'Chấm' },
      { t: '\\ddot{#0}', p: '\\ddot{x}', h: 'Hai chấm' },
      { t: '\\overparen{#0}', p: '\\overparen{AB}', h: 'Cung' },
      { t: '\\overbrace{#0}^{#?}', h: 'Ngoặc nhọn trên' },
      { t: '\\underbrace{#0}_{#?}', h: 'Ngoặc nhọn dưới' },
      { t: '\\overset{#?}{#0}', h: 'Ghi phía trên' },
      { t: '\\underset{#?}{#0}', h: 'Ghi phía dưới' },
      { t: '\\xrightarrow{#0}', h: 'Mũi tên có chữ' },
      { t: '\\xrightarrow[#?]{#0}', h: 'Mũi tên chữ trên & dưới' },
      { t: '\\xleftarrow{#0}', h: 'Mũi tên trái có chữ' },
      { t: '\\boxed{#0}', h: 'Đóng khung' },
      { t: '\\cancel{#0}', h: 'Gạch chéo (rút gọn)' },
    ]),
  },
  {
    id: 'greek', label: 'Hy Lạp',
    items: S(['\\alpha', '\\beta', '\\gamma', '\\delta', '\\varepsilon', '\\epsilon', '\\zeta', '\\eta', '\\theta', '\\vartheta',
      '\\iota', '\\kappa', '\\lambda', '\\mu', '\\nu', '\\xi', '\\pi', '\\rho', '\\sigma', '\\tau', '\\upsilon', '\\varphi',
      '\\phi', '\\chi', '\\psi', '\\omega', '\\Gamma', '\\Delta', '\\Theta', '\\Lambda', '\\Xi', '\\Pi', '\\Sigma',
      '\\Upsilon', '\\Phi', '\\Psi', '\\Omega']),
  },
  {
    id: 'ops', label: 'Toán tử & Quan hệ',
    items: S(['+', '-', '\\pm', '\\mp', '\\times', '\\div', '\\cdot', '\\circ', '\\ast', '\\oplus', '\\otimes',
      '=', '\\ne', '\\approx', '\\equiv', '\\sim', '\\simeq', '\\cong', '\\propto', '<', '>', '\\le', '\\ge',
      '\\leqslant', '\\geqslant', '\\ll', '\\gg', '\\infty', '\\partial', '\\nabla', '\\hbar', '\\ell', '\\%',
      "'", '!', '\\mid', '\\nmid', { t: '#0 \\,\\vdots\\, #?', p: 'a\\,\\vdots\\,b', h: 'Chia hết' }]),
  },
  {
    id: 'arrows', label: 'Mũi tên & Logic',
    items: S(['\\to', '\\leftarrow', '\\leftrightarrow', '\\Rightarrow', '\\Leftarrow', '\\Leftrightarrow', '\\longrightarrow',
      '\\Longrightarrow', '\\Longleftrightarrow', '\\mapsto', '\\uparrow', '\\downarrow', '\\nearrow', '\\searrow',
      '\\rightleftharpoons', '\\forall', '\\exists', '\\nexists', '\\neg', '\\land', '\\lor', '\\therefore',
      '\\because', '\\top', '\\bot']),
  },
  {
    id: 'sets', label: 'Tập hợp',
    items: S(['\\in', '\\notin', '\\ni', '\\subset', '\\supset', '\\subseteq', '\\supseteq', '\\not\\subset', '\\cup', '\\cap',
      '\\setminus', '\\varnothing', '\\emptyset', '\\mathbb{N}', '\\mathbb{N}^*', '\\mathbb{Z}', '\\mathbb{Q}', '\\mathbb{R}',
      '\\mathbb{C}', { t: '\\left\\{#0\\right\\}', p: '\\{a\\}', h: 'Tập hợp' },
      { t: '\\left\\{#0\\mid #?\\right\\}', p: '\\{x\\mid P\\}', h: 'Tập hợp theo tính chất' },
      { t: '\\left[#0;#?\\right]', p: '[a;b]', h: 'Đoạn' }, { t: '\\left(#0;#?\\right)', p: '(a;b)', h: 'Khoảng' },
      { t: '\\overline{#0}', p: '\\overline{A}', h: 'Phần bù' }]),
  },
  {
    id: 'geo', label: 'Hình học',
    items: S(['\\triangle', '\\angle', '\\widehat{ABC}', '\\perp', '\\parallel', '\\nparallel', '\\sim', '\\cong',
      '^{\\circ}', "'", "''", '\\overrightarrow{AB}', '\\overline{AB}', '\\square', '\\odot', '\\pi',
      { t: '\\left(#0\\right)', p: '(O)', h: 'Đường tròn (O)' },
      { t: '\\left(#0;#?\\right)', p: '(O;R)', h: 'Đường tròn tâm, bán kính' },
      { t: '\\mathrm{S}_{#0}', p: '\\mathrm{S}_{ABC}', h: 'Diện tích' },
      { t: '\\mathrm{V}_{#0}', p: '\\mathrm{V}_{S.ABC}', h: 'Thể tích' },
      { t: '\\mathrm{d}\\left(#0,#?\\right)', p: '\\mathrm{d}(M,\\Delta)', h: 'Khoảng cách' }]),
  },
  {
    id: 'func', label: 'Hàm số',
    items: S(['\\sin', '\\cos', '\\tan', '\\cot', '\\arcsin', '\\arccos', '\\arctan', '\\sinh', '\\cosh', '\\ln', '\\lg', '\\exp',
      { t: '\\log_{#?}#0', p: '\\log_a b', h: 'Logarit cơ số a' },
      { t: '\\mathrm{e}^{#0}', p: '\\mathrm{e}^x', h: 'Hàm mũ e' },
      { t: '#0!', p: 'n!', h: 'Giai thừa' },
      { t: '\\mathrm{C}_{#?}^{#?}', p: '\\mathrm{C}_n^k', h: 'Tổ hợp' },
      { t: '\\mathrm{A}_{#?}^{#?}', p: '\\mathrm{A}_n^k', h: 'Chỉnh hợp' },
      { t: '\\mathrm{P}_{#0}', p: '\\mathrm{P}_n', h: 'Hoán vị' },
      { t: '\\mathrm{P}\\left(#0\\right)', p: '\\mathrm{P}(A)', h: 'Xác suất' },
      { t: '\\overline{#0}', p: '\\overline{abc}', h: 'Số có nhiều chữ số' },
      { t: '\\operatorname{#0}', p: '\\operatorname{f}', h: 'Tên hàm tự đặt' },
      '\\det', '\\gcd', '\\max', '\\min', { t: '\\mathrm{i}', p: '\\mathrm{i}', h: 'Đơn vị ảo' }]),
  },
  {
    id: 'chem', label: 'Hoá học',
    items: S([
      { t: '\\mathrm{#0}', p: '\\mathrm{NaCl}', h: 'Công thức hoá học (chữ đứng)' },
      { t: '\\mathrm{#0}_{#?}', p: '\\mathrm{H}_2', h: 'Nguyên tố có chỉ số' },
      { t: '^{#?+}', p: '\\mathrm{Fe}^{3+}', h: 'Ion dương' },
      { t: '^{#?-}', p: '\\mathrm{SO}_4^{2-}', h: 'Ion âm' },
      { t: '\\xrightarrow{t^{\\circ}}', p: '\\xrightarrow{t^{\\circ}}', h: 'Nhiệt độ' },
      { t: '\\xrightarrow[#?]{t^{\\circ}}', p: '\\xrightarrow[\\text{xt}]{t^{\\circ}}', h: 'Nhiệt độ, xúc tác' },
      { t: '\\xrightarrow{#0}', h: 'Điều kiện phản ứng' },
      '\\rightarrow', '\\longrightarrow', '\\rightleftharpoons', '\\uparrow', '\\downarrow',
      { t: '\\overset{+#?}{\\mathrm{#0}}', p: '\\overset{+2}{\\mathrm{Fe}}', h: 'Số oxi hoá' },
      { t: '{}_{#?}^{#?}\\mathrm{#0}', p: '{}_{6}^{14}\\mathrm{C}', h: 'Đồng vị / hạt nhân' },
      { t: '\\Delta H', p: '\\Delta H', h: 'Biến thiên enthalpy' },
      { t: '\\mathrm{mol}', p: '\\mathrm{mol}' }, { t: '\\mathrm{M}', p: '\\mathrm{M}' },
      { t: '\\left[#0\\right]', p: '[\\mathrm{H}^+]', h: 'Nồng độ' }]),
  },
  {
    id: 'style', label: 'Kiểu chữ & Cách',
    items: S([
      { t: '\\mathrm{#0}', p: '\\mathrm{Ab}', h: 'Chữ đứng' },
      { t: '\\mathbf{#0}', p: '\\mathbf{Ab}', h: 'Chữ đậm' },
      { t: '\\boldsymbol{#0}', p: '\\boldsymbol{\\alpha}', h: 'Ký hiệu đậm' },
      { t: '\\mathit{#0}', p: '\\mathit{Ab}', h: 'Chữ nghiêng' },
      { t: '\\mathbb{#0}', p: '\\mathbb{R}', h: 'Chữ kép' },
      { t: '\\mathcal{#0}', p: '\\mathcal{L}', h: 'Chữ viết tay' },
      { t: '\\mathfrak{#0}', p: '\\mathfrak{g}', h: 'Chữ Gothic' },
      { t: '\\text{#0}', p: '\\text{Văn bản}', h: 'Văn bản' },
      { t: '\\,', p: 'a\\,b', h: 'Cách hẹp' },
      { t: '\\;', p: 'a\\;b', h: 'Cách vừa' },
      { t: '\\quad', p: 'a\\quad b', h: 'Cách rộng' },
      { t: '\\qquad', p: 'a\\qquad b', h: 'Cách rất rộng' },
    ]),
  },
];

/** LaTeX để vẽ trên nút: thay ô trống bằng khung vuông. */
export function previewLatex(item) {
  if (item.p) return item.p;
  return item.t.replace(/#0|#\?|#@/g, '\\square');
}
